### ISSUE TITLE
bad parameter reference at inlining (regression)

### ISSUE THREAD

**Issue by TomasMikula** [scalatest/scalatest#2030] opened 2021-05-14 16:08 UTC
Scalatest 3.2.9 (Scala 3.0.0)

Scastie: https://scastie.scala-lang.org/bS9fESLzT6OPvUFDKblNDw

```scala
import org.scalatest.funsuite.AnyFunSuite

class Tests extends AnyFunSuite {

  test("foo") {
    case class Pair[X, Y](
      x: X,
      y: Y,
    )
  }

}
```

results in this error when compiling

```
bad parameter reference Pair.this.X at inlining
the parameter is type X in class Pair but the prefix (Pair.this : Pair[X, Y])
does not define any corresponding arguments.
idx = 0, args = List()
```

It used to compile fine with Scalatest 3.2.8 (Scala 3.0.0-RC3).

**Comment by cheeseng** [comment] 2021-05-17 03:49
@TomasMikula I took a look at this, and the problem can be minimized to this without ScalaTest: 

```
class TestSuite {
  inline def test(fun: => Any): Any = fun
  test {
    case class Pair[X, Y](
      x: X,
      y: Y,
    )
    () 
  }
}
```

I have created an example project here: 

https://github.com/cheeseng/scala3-case-class-inline-problem

I'll try to reach the dotty gitter and see if we can find a cause, for now the workaround may be is to move the case class declaration out of the test block.

**Comment by cheeseng** [comment] 2021-05-18 13:29
@TomasMikula Fyi I submitted a ticket here: https://github.com/lampepfl/dotty/issues/12508

**Comment by TomasMikula** [comment] 2021-05-18 17:31
Great, thank you!

**Comment by cheeseng** [comment] 2022-04-15 08:32
@TomasMikula Fyi the problem shall be fixed in the upcoming Scala 3.1.3.

**Comment by TomasMikula** [comment] 2022-04-15 14:51
👍 Thank you @cheeseng

**Comment by cheeseng** [comment] 2022-06-25 07:05
@TomasMikula Fyi Scala 3.1.3 is released, and I have updated the example project to 3.1.3 and the problem is fixed now.

Cheers.

**Closed by cheeseng** 2022-06-25 07:05 UTC
