### ISSUE TITLE
class loading problem when `  character is used in package declaration or imports

### ISSUE THREAD

**Issue by dawrut** [scalatest/scalatest#536] opened 2015-03-28 22:52 UTC
When class is declared in a package containing keyword in ` characters, ScalaTest cannot resolve the classes from classpath using JetBrains IntelliJ.

Example:

Unable to load a Suite class. This could be due to an error in your runpath. Missing class: foo.`type`.Bar
java.lang.ClassNotFoundException: foo.`type`.Bar
    at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    at org.scalatest.tools.Runner$$anonfun$35.apply(Runner.scala:2438)
    at org.scalatest.tools.Runner$$anonfun$35.apply(Runner.scala:2436)
    at scala.collection.TraversableLike$$anonfun$filterImpl$1.apply(TraversableLike.scala:259)
    at scala.collection.immutable.List.foreach(List.scala:381)
    at scala.collection.TraversableLike$class.filterImpl(TraversableLike.scala:258)
    at scala.collection.TraversableLike$class.filter(TraversableLike.scala:270)
    at scala.collection.AbstractTraversable.filter(Traversable.scala:104)
    at org.scalatest.tools.Runner$.doRunRunRunDaDoRunRun(Runner.scala:2436)
    at org.scalatest.tools.Runner$$anonfun$runOptionallyWithPassFailReporter$2.apply(Runner.scala:1044)
    at org.scalatest.tools.Runner$$anonfun$runOptionallyWithPassFailReporter$2.apply(Runner.scala:1043)
    at org.scalatest.tools.Runner$.withClassLoaderAndDispatchReporter(Runner.scala:2722)
    at org.scalatest.tools.Runner$.runOptionallyWithPassFailReporter(Runner.scala:1043)
    at org.scalatest.tools.Runner$.run(Runner.scala:883)
    at org.scalatest.tools.Runner.run(Runner.scala)
    at org.jetbrains.plugins.scala.testingSupport.scalaTest.ScalaTestRunner.runScalaTest2(ScalaTestRunner.java:138)
    at org.jetbrains.plugins.scala.testingSupport.scalaTest.ScalaTestRunner.main(ScalaTestRunner.java:28)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at com.intellij.rt.execution.application.AppMain.main(AppMain.java:140)

where 

class Bar is located in foo.type.
similarly, the issue reproduces in sbt

**Comment by cheeseng** [comment] 2015-09-10 09:22
@dawrut Sorry I may not get what you meant, here's what I tried with: 

```
package foo.`type`

import org.scalatest._

class Bar extends FunSuite {

  test("here!!") {}

}

```

The following seems to be working correctly in sbt: 

```
sbt> test-only foo.type.
```

Is that what you meant by having ` in the package declaration?

**Comment by bvenners** [comment] 2016-02-12 06:44
@dawrut we did not hear back from you on how to reproduce this issue, so I'm closing the issue. If you are still experiencing the problem please post here and I'll reopen the issue.

**Closed by bvenners** 2016-02-12 06:44 UTC
