### ISSUE TITLE
Add PropertyChecks for scala.js on 3.0.0

### ISSUE THREAD

**Issue by InTheNow** [scalatest/scalatest#631] opened 2015-06-29 10:17 UTC
I'm porting typelevel Discipline to sjs and scalcheck integration is a must have. This is also the case for Cats and supporting modules. 

Locally I got this working fine on a local build, but on an older versiion od scalatest-js. Diffs :

```diff
diff --git a/project/GenScalaTestJS.scala b/project/GenScalaTestJS.scala
index 751747b..0ab380c 100644
--- a/project/GenScalaTestJS.scala
+++ b/project/GenScalaTestJS.scala
@@ -371,9 +371,9 @@ object GenScalaTestJS {
       ), targetDir) ++
     copyDir("scalatest/src/main/scala/org/scalatest/prop", "org/scalatest/prop",
       List(
-        //"Configuration.scala",
-        //"Checkers.scala",
-        //"PropertyChecks.scala",
+        "Configuration.scala",
+        "Checkers.scala",
+        "PropertyChecks.scala",
         "Whenever.scala"
       ), targetDir) ++
     copyDir("scalatest/src/main/scala/org/scalatest/concurrent", "org/scalatest/concurrent",
```

```diff
diff --git a/scalatest/src/main/scala/org/scalatest/prop/Checkers.scala b/scalatest/src/main/scala/org/scalatest/prop/Checkers.scala
index a6e1602..dd38bf9 100644
--- a/scalatest/src/main/scala/org/scalatest/prop/Checkers.scala
+++ b/scalatest/src/main/scala/org/scalatest/prop/Checkers.scala
@@ -225,6 +225,7 @@ repeatedly pass generated data to the function. In this case, the test data is c
  *
  * @author Bill Venners
  */
+// SCALATESTJS-ONLY @scala.scalajs.js.annotation.JSExportDescendentClasses(ignoreInvalidDescendants = true)
 trait Checkers extends Configuration {
 

```

**Comment by bvenners** [comment] 2015-06-29 13:29
Hi Alistair,

Sorry I didn't realized that wasn't in there. We'll look into it.

Bill

**Comment by InTheNow** [comment] 2015-07-10 10:01
Hi Bill - Sorry if I sound like I'm hassling you but any ideas on timelines for this, please? I'm just planning other work so would be nice to know if I should just wait a few more days or implement my plan B.

**Comment by bvenners** [comment] 2015-07-10 13:04
No please do hassle! We have so many things coming at us lately that things can get sometimes get forgotten. This seems like a simple deployment issue. I'll try and get a new milestone out pronto with this in it.

**Comment by bvenners** [comment] 2015-07-10 13:17
Can you let us know a bit more about your build. What version are you using? A long time back we didn't have this in because ScalaCheck didn't work on all the JS platforms, but once that got fixed we added this in. The latest version is 3.0.0-M6. If you're not on that, can you try it. If you still see the problem, let us know more about your build.

**Comment by InTheNow** [comment] 2015-07-10 13:22
thx - will upgrade to M6 and give feedback soon.

**Comment by InTheNow** [comment] 2015-07-10 18:14
Still no joy with M6, but works with a local, hacked build of scalatest. Build is at https://github.com/InTheNow/discipline/tree/topic/sjs and the diff for branch 3.0.x is:

```diff
diff --git a/project/scalatest.scala b/project/scalatest.scala
index caffb8b..8ab54d2 100644
--- a/project/scalatest.scala
+++ b/project/scalatest.scala
@@ -132,7 +132,7 @@ object ScalatestBuild extends Build {
   )
 
   def scalacheckDependency(config: String) =
-    "org.scalacheck" %% "scalacheck" % "1.12.3" % config
+    "org.scalacheck" %% "scalacheck" % "1.12.4" % config
 
   def crossBuildLibraryDependencies(theScalaVersion: String) =
     CrossVersion.partialVersion(theScalaVersion) match {
@@ -173,7 +173,8 @@ object ScalatestBuild extends Build {
 
   def scalatestJSLibraryDependencies =
     Seq(
-      "org.scala-js" %% "scalajs-test-interface" % "0.6.4"
+      "org.scala-js" %% "scalajs-test-interface" % "0.6.4",
+      "org.scalacheck" %% "scalacheck_sjs0.6" % "1.12.4"
     )
 
   def scalatestTestOptions =
@@ -499,8 +500,8 @@ object ScalatestBuild extends Build {
         (baseDirectory, sourceManaged in Compile, version, scalaVersion) map genFiles("gentables", "GenTable.scala")(GenTable.genMainForScalaJS),
       sourceGenerators in Compile <+=
         (baseDirectory, sourceManaged in Compile, version, scalaVersion) map genFiles("genmatchers", "MustMatchers.scala")(GenMatchers.genMainForScalaJS),
-      /*genMustMatchersTask,
       genGenTask,
+      /*genMustMatchersTask,
       genTablesTask,
       genCodeTask,
       genCompatibleClassesTask,
diff --git a/scalatest/src/main/scala/org/scalatest/prop/Checkers.scala b/scalatest/src/main/scala/org/scalatest/prop/Checkers.scala
index 67fb8f3..326a53d 100644
--- a/scalatest/src/main/scala/org/scalatest/prop/Checkers.scala
+++ b/scalatest/src/main/scala/org/scalatest/prop/Checkers.scala
@@ -228,6 +228,8 @@ repeatedly pass generated data to the function. In this case, the test data is c
  *
  * @author Bill Venners
  */
+ // SCALATESTJS-ONLY @scala.scalajs.js.annotation.JSExportDescendentClasses(ignoreInvalidDescendants = true)
+
 trait Checkers extends Configuration {
 
   /**

```

**Comment by cheeseng** [comment] 2015-07-11 11:11
Hi Allstair,

Seems like incompatible issue between scalacheck 1.12.3 and 1.12.4, I have
submitted a PR to update to use scalacheck 1.12.4:

https://github.com/scalatest/scalatest/pull/639

The JSExportDescendentClasses that you added to Checkers is not required
imho, or I could be missing something, do you mind to give the branch a try
to see if it fixes your problem?

Thanks.

Chee Seng

**Comment by InTheNow** [comment] 2015-07-11 13:43
Yes, works fine from branch! LGTM & thanks

**Comment by bvenners** [comment] 2015-07-11 16:34
I have merged this in and am having trouble deploying 3.0.0-M7 because of network issues. Hopefully I'll get it out before my flight, as I was unable to deploy from the plane wifi on the way here. If not in the next hour, it will be tonight.

**Comment by bvenners** [comment] 2015-07-11 18:35
No luck even on the 4th attempt. I'll try again once I get back home. I think the problem is just bad network connectivity.

**Comment by bvenners** [comment] 2015-07-12 06:44
Yes, it was just network issues. Deployed fine first attempt from home. Please try 3.0.0-M7.

Thanks.

Bill

**Closed by bvenners** 2015-07-12 06:44 UTC

**Comment by InTheNow** [comment] 2015-07-12 06:48
Works perfectly :) Many thanks
