### ISSUE TITLE
intercept or a variant should thrown unexpected exceptions

### ISSUE THREAD

**Issue by agile-jordi** [scalatest/scalatest#702] opened 2015-09-15 09:46 UTC
When using intercept to check that a block of code throws an exception, it fails gracefully when no exception is thrown at all. But when an unexpected exception is thrown, the error message is not useful at all, since the details of the exception actually thrown and its stack trace are lost.

In my opinion, intercept itself (or a variant of it) should throw any unexpected exception, as any other test usually does when an unexpected exception is produced. This method should only cause a specific failure when no exception is thrown at all.

One such a method could be (note that the error message should be propery internationalized):

```
def interceptOrThrow[T <: AnyRef](f: => Any)(implicit manifest: Manifest[T]): T = {
    val clazz = manifest.runtimeClass.asInstanceOf[Class[T]]
     try {
      f
      fail(s"An exception of type ${clazz.getName} was expected")
    }
    catch {
      case u: Throwable if clazz.isAssignableFrom(u.getClass) => u.asInstanceOf[T]
    }
  }
```

If there is interest, I could issue a pull request with a completed version of this method.

**Comment by bvenners** [comment] 2015-09-15 11:36
Hi Jordi,

The original exception is included as the cause of the thrown TFE. The TFE gives you a stack depth that points to the failing line of code:

scala> intercept[ArrayIndexOutOfBoundsException] { "hi".charAt(-1) }
org.scalatest.exceptions.TestFailedException: Expected exception java.lang.ArrayIndexOutOfBoundsException to be thrown, but java.lang.StringIndexOutOfBoundsException was thrown
  at org.scalatest.Assertions$class.newAssertionFailedException(Assertions.scala:503)
  at org.scalatest.Matchers$.newAssertionFailedException(Matchers.scala:7694)
  at org.scalatest.Assertions$class.intercept(Assertions.scala:797)
  at org.scalatest.Matchers$.intercept(Matchers.scala:7694)
  ... 43 elided
Caused by: java.lang.StringIndexOutOfBoundsException: String index out of range: -1
  at java.lang.String.charAt(String.java:686)
  at $anonfun$1.apply$mcC$sp(<console>:23)
  at $anonfun$1.apply(<console>:23)
  at $anonfun$1.apply(<console>:23)
  at org.scalatest.Assertions$class.intercept(Assertions.scala:790)
  ... 44 more

Are you able to look at this cause in the report? If not, please let me know how you are getting a report.

Thanks.

Bill

**Comment by agile-jordi** [comment] 2015-09-30 10:56
Hello Bill,

Sorry for not replying earlier, I was out for some weeks.

You are completely right in that I can have the stack trace of the original
exception, and I had missed it completely.

I'd still throw the exception instead of reporting a failed assertion.
After all, any other unexpected exception thrown in any  other test would
behave differently compared to an unexpected exception thrown inside an
intercept. But this is just a minor difference in opinion, and not that
important once I realized the original stack trace is not lost.

Thank you very much for your prompt response!

Jordi Pradel
@agile_jordi


>>| agilogy
Carrer Zamora 46-48, 4rt 4a
08005 Barcelona
+34 93 354 11 78

2015-09-15 13:36 GMT+02:00 Bill Venners <notifications@github.com>:

**Comment by bvenners** [comment] 2015-09-30 13:21
No worries. Closing.

**Closed by bvenners** 2015-09-30 13:21 UTC
