### ISSUE TITLE
Scalatest failures do not appear in Jenkins

### ISSUE THREAD

**Issue by lukiano** [scalatest/scalatest#4] opened 2013-04-10 14:45 UTC
I think that JunitXMLReporter is generating an XML that is not being recognized by Jenkins.
It looks like the issue is that there may be space (or newline) between &lt;property&gt; and &lt;/property&gt;.

One solution is to use  &lt;property name="path.separator" value=";" /&gt;, ending with /&gt;

**Comment by bvenners** [comment] 2015-04-08 21:51
Unable to reproduce this, so closing.

**Closed by bvenners** 2015-04-08 21:51 UTC

**Comment by vanaf** [comment] 2020-06-03 10:13
As a workaround we use xslt transformation:
```
            <!--Fix validity of scalatest junit xmls. See https://github.com/scalatest/scalatest/issues/4 -->
            <plugin>
                <groupId>org.codehaus.mojo</groupId>
                <artifactId>xml-maven-plugin</artifactId>
                <executions>
                    <execution>
                        <phase>test</phase>
                        <goals>
                            <goal>transform</goal>
                        </goals>
                    </execution>
               </executions>
               <configuration>
                   <transformationSets>
                       <transformationSet>
                           <dir>${project.build.directory}/surefire-reports</dir>
                           <outputDir>${project.build.directory}/surefire-reports</outputDir>
                           <stylesheet>scalatest.xslt</stylesheet>
                       </transformationSet>
                   </transformationSets>
               </configuration>
            </plugin>
```
scalatest.xslt:
```
<?xml version="1.0"?>
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
  <xsl:output method="xml"/>

  <!-- identity transform -->
  <xsl:template match="@*|node()">                
    <xsl:copy>
      <xsl:apply-templates select="@*|node()" />
    </xsl:copy>
  </xsl:template>

  <xsl:template match="property">
    <property><xsl:copy-of select="@*" /> </property>
  </xsl:template>

</xsl:stylesheet>
```
