### ISSUE TITLE
Referring to non-existent class Lorg_scalactic_exceptions_NullArgumentException

### ISSUE THREAD

**Issue by aborg0** [scalatest/scalatest#633] opened 2015-07-03 19:59 UTC
After updating to Scala 2.11.7, Scala.js 0.6.4, ScalaTest 3.0.0-M4 (not used before), I got a [linkage error](https://github.com/aborg0/underscore.scala.js/blob/failing_scalatest/error_scalaJSLinkingUnitClassPath_out.txt) run with Rhino (`test`) on my project (kept only the errors from `target\streams\test\scalaJSLinkingUnitClasspath\$global\streams`).
The release notes of [Scala.js 0.6.4](http://www.scala-js.org/news/2015/07/03/announcing-scalajs-0.6.4/) suggests the problem was already there (which manifests in a Future timeout when using 2.11.6 with 0.6.3). It seems this might be a problem with the 3.0.0-M4 release for Scala.js. (Probably there are smaller reproductions. I have not created a non-failing test yet. I am not sure this is a problem with ScalaTest or Scalactic or my configuration/usage.)

**Comment by bvenners** [comment] 2015-07-03 20:05
I hadn't gotten the memo about Scala.js 0.6.4. I'll try building and testing ScalaTest with it. Perhaps there's some inconsistency in which case we'll make a new milestone release just for 0.6.4. But it should be able to find NullArgumentException unless it is really missing. I'll investigate.

**Comment by bvenners** [comment] 2015-07-03 20:13
Actually the thought occurred to me that since NullArgumentException is part of Scalactic, and you didn't mention the Scalactic version number, perhaps they are out of sync? They should always be exactly the same. So make sure your Scalactic version (if you have a scalactic dependency that is) is also 3.0.0-M3.

**Comment by aborg0** [comment] 2015-07-03 20:24
No, it seems to work the same way when I added the line `libraryDependencies += "org.scalactic" %%% "scalactic" % "3.0.0-M4" % "test"` to `build.sbt`. (The project with failing to link test is available in [this branch](https://github.com/aborg0/underscore.scala.js/tree/failing_scalatest).)

**Comment by bvenners** [comment] 2015-07-03 21:21
I'm currently unable to get the Scalactic tests to run under 0.6.4, getting this error: https://groups.google.com/forum/?fromgroups#!topic/scala-js/a6jZNx6WMjs

**Comment by cheeseng** [comment] 2015-07-04 14:05
Hi Gabor, Bill,

I believe this problem exists also with scala-js 0.6.3, and the problem is
that the new org.scalactic.exceptions is missing in the osgi publish
settings, here's the PR to fix it:

https://github.com/scalatest/scalatest/pull/634

Bill's problem on 0.6.4 seems new, hopefully we'll get a good response from
scala-js team.  :)

Best Regards,
Chee Seng

**Comment by bvenners** [comment] 2015-07-04 17:24
I'll merge in that PR. On my other build problem with 0.6.4, I realized that I was trying to build with Java 8 not Java 6. I'll try Java 6 and hope the problem goes away. I think perhaps I should do a release under 0.6.3 anyway with the OSGI problem fixed, in case people need to use that not 0.64.

**Comment by bvenners** [comment] 2015-07-04 20:19
The PR is merged in, but I confirmed I still have the IR problem when compiling under Java 6, so it is a real problem. Hopefully soon we can some suggestions from the Scala.js folks.

**Comment by bvenners** [comment] 2015-07-04 21:24
3.0.0-M5 is now released with the OSGI fix, but by necessity it depends on Scala.js 0.6.3. Once I can get the tests to run under 0.6.4 I'll deploy another milestone.

**Comment by bvenners** [comment] 2016-02-12 11:45
We are now on Scala.js 0.6.5, but we never went back to close the ticket. Closing now.

**Closed by bvenners** 2016-02-12 11:45 UTC
